version: 2

builds:
  - main: .
    binary: gogo
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-gnu
          - CXX=zig c++ -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-gnu
          - CXX=zig c++ -target aarch64-linux-gnu
      - goos: darwin
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-macos
          - CXX=zig c++ -target x86_64-macos
      - goos: darwin
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-macos
          - CXX=zig c++ -target aarch64-macos

changelog:
  sort: asc
